package android.feetme.fr.punchme.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import android.feetme.fr.punchme.dao.Glove;

import android.feetme.fr.punchme.dao.GloveDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gloveDaoConfig;

    private final GloveDao gloveDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gloveDaoConfig = daoConfigMap.get(GloveDao.class).clone();
        gloveDaoConfig.initIdentityScope(type);

        gloveDao = new GloveDao(gloveDaoConfig, this);

        registerDao(Glove.class, gloveDao);
    }
    
    public void clear() {
        gloveDaoConfig.getIdentityScope().clear();
    }

    public GloveDao getGloveDao() {
        return gloveDao;
    }

}
