package android.feetme.fr.punchme.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GLOVE".
 */
public class Glove {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String address;
    private Integer side;
    private Integer sensorNb;
    private String serialNumber;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Glove() {
    }

    public Glove(Long id) {
        this.id = id;
    }

    public Glove(Long id, String name, String address, Integer side, Integer sensorNb, String serialNumber) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.side = side;
        this.sensorNb = sensorNb;
        this.serialNumber = serialNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    public Integer getSide() {
        return side;
    }

    public void setSide(Integer side) {
        this.side = side;
    }

    public Integer getSensorNb() {
        return sensorNb;
    }

    public void setSensorNb(Integer sensorNb) {
        this.sensorNb = sensorNb;
    }

    public String getSerialNumber() {
        return serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
